replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/web.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: APPINSIGHTS_INSTRUMENTATIONKEY
    - name: ApiUrl
    - name: ApiUrlShoppingCart
    - name: UseB2C
    - name: REACT_APP_USE_B2C
    - name: B2CAuth__ClientId
    - name: B2CAuth__Authority
    - name: B2CAuth__Scopes
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
